name: Pandora2d CI

on:
  push:
  schedule:
   - cron:  0 2 * * *


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-cov
        pip install pytest-mock
        pip install pytest-monitor
        pip install pytest-html
        pip install codecov
        pip install build
    - name: Install Pandora2d
      run: |
        pip install .
    - name: Test with pytest
      run: |
        export NUMBA_DISABLE_JIT="1"
        pytest -m "unit_tests and not notebook_tests and not plugin_tests" --html=unit-test-report.html --cov-config=.coveragerc --cov-report xml --cov
        pytest -m "functional_tests" --html=functional-test-report.html
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
    - name: Create source distrubition
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      run: |
        python -m build --sdist
    - name: Publish package on pypi
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
       verbose: true
       user: __token__
       password: ${{ secrets.PYPI_API_TOKEN }}
